nginx:
  image: oxynux/nginx
  ports:
    - "80:8000"
  volumes:
    - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
  links:
    - node
node:
  build: node
  volumes:
    - ./node/app/server.js:/usr/src/app/server.js
  environment:
    - MONGO_URL=mongodb://mongo:27017/db
  links:
    - mongo
mongo:
  image: mongo:3.4
  volumes:
    - ./mongodb:/data/db